project import
vovkka/Todolist pull request #1
Opened 2022-10-09 11:21 UTC by vovkka

2022-10-09 11:22 UTC, Sussia commented on project.py
> +
Поехали отступы

2022-10-09 11:58 UTC, vovkka commented on project.py
> +
((

2022-10-09 11:58 UTC, vovkka commented on project.py
> +
((

2022-10-09 12:02 UTC, Sussia requested changes

2022-10-09 12:02 UTC, Sussia commented on project.py
> +	def get_operation(self):
Зачем self?

2022-10-09 12:02 UTC, Sussia commented on project.py
> +
Пустая строчка

2022-10-10 12:36 UTC, vovkka commented on project.py
> +	def get_operation(self):
Надо

2022-10-12 13:58 UTC, merged