Разделение ответственности меню и пункта меню
vovkka/Todolist pull request #12
Opened 2022-10-21 15:04 UTC by vovkka

2022-10-21 15:05 UTC, vovkka commented
Одно что мне не нравится, чтобы в консоли был отступ от прошлых сообщений, приходится пустой print() в print_menu() добавить

2022-10-21 15:32 UTC, Sussia requested changes
Еще у тебя экземпляр меню не создается, используешь статический вызов print_menu, сделай экзепляр

2022-10-21 15:32 UTC, Sussia commented on project.py
> +		options = [Operation.addTask, Operation.viewTask, Operation.viewListOfTasks, Operation.deleteTask, Operation.findTask, Operation.exit]
массив храни в классе

2022-10-21 15:32 UTC, Sussia commented on project.py
> +			print(Operation.__str__(option))
можно просто str(option)

2022-10-21 15:35 UTC, Sussia commented
Почему нужен отступ? Где перед этим он не появляется? Или в смысле чтобы типо визуально отделить меню от остального вывода? Если второй вариант, то это норм решение

2022-10-22 00:30 UTC, vovkka commented
Да, визуально

2022-10-22 00:30 UTC, vovkka commented
> Еще у тебя экземпляр меню не создается, используешь статический вызов print_menu, сделай экзепляр
> 

А почему именно экземпляр, в чем разница?

2022-10-24 14:32 UTC, vovkka commented
Ребазе сделал. Я там капец чето все попутал, не то не в те позаливал, когда хочу чето запушить случайно, то случайно пулю и т д. В общем если я сделал что-то не так, то я не специально)

2022-10-24 14:55 UTC, Sussia commented on project.py
> +			print(Operation.__str__(option))
Так не надо от Operation его вызывать, а просто `print(str(option))`

`__str__` это служебная функция, которая позволяет преобразовывать тип к строке с помощью функции str() питоновской

2022-10-24 14:57 UTC, Sussia commented on project.py
> +		options = [Operation.addTask, Operation.viewTask, Operation.viewListOfTasks, Operation.deleteTask, Operation.findTask, Operation.exit]
Массив у тебя сейчас в методе
Инит делать не обязательно, чтобы использовать это поле с self, он и так видит, если ты поле в классе объявляешь

Код который я в issue сделал работает, я проверял

2022-10-24 15:35 UTC, vovkka commented on project.py
> +			print(Operation.__str__(option))
А зачем тогда __str__ если она нигде не используется

2022-10-25 11:43 UTC, vovkka commented on project.py
> +			print(Operation.__str__(option))
> можно просто str(option)

я тебе больше скажу, str() вообще не нужен. Эта функция сама автоматически применяется на все экземпляры класса когда ты их хочешь запринтить

2022-10-25 12:10 UTC, closed without merging